package com.aberdeenuni.acse;
/**
 * 
 */

public enum ParserType
{
	ANDROID_SAX_NEWS, 
	ANDROID_SAX_EVENTS, 
	ANDROID_SAX_FACEBOOK,
	ANDROID_SAX_YOUTUBE,
	ANDROID_SAX_SLIDESHARE,
	ANDROID_SAX_GUARDIAN,
	ANDROID_SAX_BBC,
	ANDROID_SAX_REUTERS,
	ANDROID_SAX_RELU,
	ANDROID_SAX_PPPC;
}
